version: '3.1'
services:
  zungen-admin:
    image: $REGISTRY_ADDRESS/zungen-admin:$CI_COMMIT_SHORT_SHA
    restart: always
    network_mode: host
    environment:
      - profileActive=${RUN_ENV}
      - DUBBO_IP_TO_REGISTRY= 192.168.1.172
    volumes:
      - "/logs/assemble:/logs"
    logging:
           driver: "json-file"
           options:
              max-size: "5m"
